### PR TITLE
fix grappler compilation error with TF 1.15 ~ 2.6

### PR DESCRIPTION
**Pull request by njzjz**
reported by @denghuilu

### CODE REVIEW

**Review by denghuilu — APPROVED** [review]
It works with TF-2.4.0 on my local workstation!
