### ISSUE TITLE
[BUG] Fail to run dp train with 2.2.8 (but success with 2.2.7)

### ISSUE THREAD

**Issue by link89** [deepmodeling/deepmd-kit#3218]
### Bug summary

Get error the following error when run dp train on a GPU node

```
error: libdevice not found at ./libdevice.10.bc
2024-02-01 22:45:42.137246: W tensorflow/core/framework/op_kernel.cc:1827] UNKNOWN: JIT compilation failed.
2024-02-01 22:45:42.137338: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 17091566501094239012
Traceback (most recent call last):
  File "/public/groups/ai4ec/libs/conda/deepmd/2.2.8/gpu/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1402, in _do_call
    return fn(*args)
  File "/public/groups/ai4ec/libs/conda/deepmd/2.2.8/gpu/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1385, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/public/groups/ai4ec/libs/conda/deepmd/2.2.8/gpu/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1478, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) UNKNOWN: JIT compilation failed.
         [[{{node ExponentialDecay/Floor}}]]
         [[ExponentialDecay/_163]]
  (1) UNKNOWN: JIT compilation failed.
         [[{{node ExponentialDecay/Floor}}]]
0 successful operations.
0 derived errors ignored.
```

It works well with 2.2.7. Currently our work around is to use 2.2.7 to train model and run LAMMPS with deepmd 2.2.8.

### DeePMD-kit Version

2.2.8

### TensorFlow Version

2.14.0

### How did you download the software?

Conda

### Input Files, Running Commands, Error Log, etc.

[deepmd-2.2.8.log.txt](https://github.com/deepmodeling/deepmd-kit/files/14136877/deepmd-2.2.8.log.txt)

### Steps to Reproduce

Install deepmd with the following command
```
CONDA_OVERRIDE_CUDA="11.8" conda create -p deepmd/2.2.8/gpu deepmd-kit=2.2.8=cuda118py310*  lammps horovod -c conda-forge 
```

And then run `dp train`

**Comment by njzjz** [comment]
Upstream xref:
- https://github.com/conda-forge/tensorflow-feedstock/issues/296
- https://github.com/conda-forge/cudatoolkit-feedstock/issues/96

**Comment by biglinn** [comment]
When I perform dogen 'run' with deepmd-kit 2.2.8 and tensorflow 2.15.0, there is a similar problem about tensorflow.

**Comment by njzjz** [comment]
> When I perform dogen 'run' with deepmd-kit 2.2.8 and tensorflow 2.15.0, there is a similar problem about tensorflow.

The problem on TF 2.15 should have been fixed in https://github.com/conda-forge/tensorflow-feedstock/pull/370. It is valuable to know whether the new build still has the problem.

**Comment by biglinn** [comment]
> > When I perform dogen 'run' with deepmd-kit 2.2.8 and tensorflow 2.15.0, there is a similar problem about tensorflow.
> 
> The problem on TF 2.15 should have been fixed in [conda-forge/tensorflow-feedstock#370](https://github.com/conda-forge/tensorflow-feedstock/pull/370). It is valuable to know whether the new build still has the problem.

Ok, I will take a try. Thanks!
In addition, I find that deepmd-kit 2.2.7 and tensorflow 2.9.0 can perform very good.

**Comment by link89** [comment]
@njzjz deepmd/2.2.9 still have this issue. One has to run `pip install nvidia-cuda-nvcc-cu11` to workaround. I guess this issue is not fixed yet.

**Comment by njzjz** [comment]
> deepmd/2.2.9 still have this issue.

@link89 the issue is not related to deepmd-kit.

**Comment by Entropy-Enthalpy** [comment]
The symlink `lib/python3.12/site-packages/nvidia/cuda_nvcc/nvvm/libdevice/libdevice.10.bc` in v3.0.0~3.1.0a0 offline packages is wrong, it shoule be `../../../../../../../nvvm/libdevice/libdevice.10.bc`, not `../../../../../../nvvm/libdevice/libdevice.10.bc`. @njzjz

**Comment by njzjz** [comment]
> The symlink `lib/python3.12/site-packages/nvidia/cuda_nvcc/nvvm/libdevice/libdevice.10.bc` in v3.0.0~3.1.0a0 offline packages is wrong, it shoule be `../../../../../../../nvvm/libdevice/libdevice.10.bc`, not `../../../../../../nvvm/libdevice/libdevice.10.bc`. [@njzjz](https://github.com/njzjz)

Fixed.
